name: Deploy visitor-counter lambda code

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
      - backend/lambda/**

jobs:
  release:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::371077785672:role/GithubActionsRole        
          aws-region: us-east-1

      - name: Install dependencies with LambCI
        uses: docker://lambci/lambda:build-python3.8
        with:
          entrypoint: pip
          args: install -r ./backend/lambda/requirements.txt --target ./backend/lambda

      - name: Zip Lambda Function
        working-directory: ./backend/lambda
        run: |
           zip -r9 visitor_count.zip . -x ./backend/lambda/requirements.txt
      
      - name: AWS Deploy
        working-directory: ./backend/lambda
        run: |
           aws lambda update-function-code --function-name visitor-count --region us-east-1 --zip-file fileb://visitor_count.zip