name: Deploy visitor-counter lambda code

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
      - backend/lambda/**

jobs:
  release:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::371077785672:role/GithubActionsRole        
          aws-region: us-east-1
      
      - name: Install python dependencies
        working-directory: ./backend/lambda
        run: |
           pip install -r backend/lambda/requirements.txt

      - name: Zip Lambda Function
        run: |
           zip -r9 visitor_count.zip ./backend/lambda
      
      - name: AWS Deploy
        run: |
           aws lambda update-function-code --function-name visitor-count --region us-east-1 --zip-file fileb://visitor_count.zip
        #run: |
        #  aws lambda update-function-code --function-name visitor-count --region us-east-1 --zip-file fileb://backend/lambda/visitor_count.zip