name: Upload Website

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
      - frontend/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::371077785672:role/GithubActionsRole        
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./frontend/ s3://forevertechstudent.com --delete